import { DM_Sans,Barlow } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Topbar from "@/components/Topbar";
import Footer from "@/components/Footer";

const dmSans  = DM_Sans({
  variable:"--font-dmSans",
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
})

const barlow = Barlow({
  variable:"--font-barlow",
  subsets:["latin"],
  weight:["100","200","300","400","500","600","700","800","900"]
})


export const metadata = {
  title: "Contained Solar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${barlow.variable} antialiased`}
      >
        <Topbar />
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
